PythonBelt3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginReg.urls', namespace='loginreg')),
    url(r'^examThree/', include('apps.examThree.urls', namespace='examThree'))
]

apps/examThree/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^update$', views.update, name='update'),
    url(r'^(?P<id>\d+)/remove$', views.remove, name='remove'),
    url(r'^(?P<id>\d+)/show$', views.show, name='show'),
    url(r'^(?P<id>\d+)/addfave$', views.addfave, name='addfave'),
]

apps/loginReg/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.index, name='LR_index'),
    url(r'^register$', views.register, name='LR_register'),
    url(r'^login$', views.login, name='LR_login'),
    url(r'^success$', views.success, name='LR_success'),
    url(r'^logout$', views.logout, name='LR_logout'),
]

apps/examThree/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import pytz

from django.utils import timezone

from time import strptime,strftime

from datetime import datetime, date, time

import datetime

from ..loginReg.models import User

class TripManager(models.Manager):
    def validate(self, postData):
        errors = {}
        now = timezone.now()
        currentDate = unicode(datetime.datetime.now().date())
        startDate = unicode(postData['startDate'])
        endDate = unicode(postData['endDate'])
        if len(postData['destination']) < 1:
            errors["Destination"] = "Destination name cannot be empty"
        if len(postData['description']) < 1:
            errors["Description"] = "Description cannot be empty"
        if len(str(postData["startDate"])) < 1:
            errors["Start Date"] = "Date cannot be empty"
        if len(str(postData["endDate"])) < 1:
            errors["End Date"] = "Date cannot be empty"
        if startDate < currentDate:
            errors["Start Date"] = "Time travel isn't real." 
        if endDate < startDate:
            errors["End Date"] = "Trip cannot end before it begins, party pooper!" 
        return errors

class Trip(models.Model):
    destination = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    startDate = models.DateField(auto_now=False, auto_now_add=False, null=True)
    endDate = models.DateField(auto_now=False, auto_now_add=False, null=True)
    favorites = models.ManyToManyField(User, related_name="userFaves")
    userAdded = models.ForeignKey(User, related_name="userAdds")
    objects = TripManager()

apps/examThree/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse

from django.contrib import messages

from datetime import date, time, datetime

import datetime

from .models import *

from ..loginReg.models import User

from django.shortcuts import render, HttpResponse, redirect

def index(request ):
    currentUser = User.objects.get(id=request.session['userid']) 
    trips = currentUser.userFaves.all()
    othersTrips = Trip.objects.exclude(favorites=currentUser)
    context = {
        "trips" : trips,
        "othersTrips": othersTrips,
    }
    return render(request,'examThree/index.html', context)

def add(request):
    return render(request,'examThree/add.html')

def update(request):
    currentUser = User.objects.get(id=request.session['userid'])
    errors = Trip.objects.validate(request.POST)
    if len(errors) > 0:
        for error in errors.iteritems():
            messages.error(request, error)
        return redirect('examThree:add')
    else:  
       Trip.objects.create(description=request.POST["description"], destination=request.POST["destination"], startDate=request.POST["startDate"], endDate=request.POST["endDate"], userAdded = currentUser)
    return redirect(reverse('examThree:index'))

def show(request, id):
    trip = Trip.objects.get(id=id)
    context = {
        "trip": trip
    }
    return render(request,'examThree/show.html', context)


def addfave(request, id):
    currentUser = User.objects.get(id=request.session['userid'])
    fave = Trip.objects.get(id=id)
    fave.favorites.add(currentUser)
    fave.save()
    return redirect(reverse('examThree:index'))


def remove(request, id):
    currentUser = User.objects.get(id=request.session['userid'])
    fave = Trip.objects.get(id=id)
    fave.favorites.remove(currentUser)
    fave.save()
    return redirect(reverse('examThree:index'))

apps/examThree/templates/examThree/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Hello! Where would you like to go?</h1>
        <form action="/examThree/update" method='POST'>
            {% csrf_token %} 
            DESTINATION: <input type="text" name="destination" value="{{trip.destination}}"> 
            DESCRIPTION: <input type="text" name="description" value="{{trip.tripDescription}}"> 
            TRAVEL START:<input type="date" name="startDate" value="{{trip.tripStart}}"> 
            TRAVEL END: <input type="date" name="endDate" value="{{task.tripEnd}}"> 
            <input type="submit" value="Add">
           </form>
           
           {% if messages %}
           <ul class="messages">
               {% for message in messages %}
               <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                   {% endfor %}
           </ul>
           {% endif %}
    <a href="{%url 'examThree:index' %}">Back to Dashboard</a>
</body>
</html>

apps/examThree/templates/examThree/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>

<body>
    <h1>Hello, {{request.session.first}}! </h1>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}

    <table>
        <thead>
            <tr>
                <th>Destination</th>
                <th>Travel Start Date</th>
                <th>Travel End Date</th>
                <th>Plan</th>
            </tr>
        </thead>
        <tbody>
            {% for trip in trips %}
            <tr>
                <td>
                    <a href="{{trip.id}}/show">{{trip.destination}}</a>
                </td>
                <br>
                <td>{{trip.startDate}}</td>
                <br>
                <td>{{trip.endDate}}</td>
                <br>
                <td>{{trip.description}}</td>
                <td>
                <a href="{{trip.id}}/remove">Nevermind</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <table>
        <h2>OTHER USERS' TRAVEL PLANS</h2>
        <thead>
            <tr>
                <th>NAME</th>
                <th>DESTINATION</th>
                <th>TRAVEL START DATE</th>
                <th>TRAVEL END DATE</th>
                <th>JOIN</th>
            </tr>
        </thead>
        <tbody>
            {% for othersTrips in othersTrips %}
            <tr>
                <td>{{othersTrips.userAdded.first}}</td>
                
                <td> <a href="{{othersTrips.id}}/show"> {{othersTrips.destination}}</a>  </td>
        
                <th>{{othersTrips.startDate}}</th>
                <th>{{othersTrips.endDate}}</th>
                <th><a href="/examThree/{{othersTrips.id}}/addfave">  Join </a> </th>

            </tr>
            {% endfor %}
        </tbody>
    </table>

    <button>
        <a href="/examThree/add">ADD A TRIP</a>
    </button>



    <button>
            <a href="{%url 'loginreg:LR_logout'%}">Logout</a>
    </button>
    

</body>

</html>

apps/examThree/templates/examThree/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    
   
        <h1>{{trip.destination}}</h1>

        <p>Planned By: {{trip.userAdded.first}}</p>
        <p>Description: {{trip.description}} </p>
        <p>Travel Date From: {{trip.startDate}}</p>
        <p>Travel Date To: {{trip.endDate}}</p>
   

    <h3>Other users joining this trip:</h3>
    {% for user in trip.favorites.all %}
        <p>{{user.first}}</p>
      
    {% endfor %}


    <a href="{%url 'examThree:index' %}">Back to Trip Dashboard</a></button>
</body>
</html>