PythonBelt3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginReg.urls', namespace='loginreg')),
    url(r'^examThree/', include('apps.examThree.urls', namespace='examThree'))
]

apps/examThree/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^update$', views.update, name='update'),
    url(r'^(?P<id>\d+)/remove$', views.remove, name='remove'),
    url(r'^(?P<id>\d+)/show$', views.show, name='show'),
    url(r'^(?P<id>\d+)/addfave$', views.addfave, name='addfave'),
]

apps/loginReg/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.index, name='LR_index'),
    url(r'^register$', views.register, name='LR_register'),
    url(r'^login$', views.login, name='LR_login'),
    url(r'^success$', views.success, name='LR_success'),
    url(r'^logout$', views.logout, name='LR_logout'),
]

apps/loginReg/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import bcrypt

import re
NAME_REGEX = re.compile(r"^[-a-zA-Z']+$")
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


class UserManager(models.Manager):
    def validate(self, postData): #declare a controller of validation for the registration checker and create an empty dictionary of errors. Checks for errors below
        errors = {}
        if len(postData['first']) < 2:
            errors["First name cannot be blank!"] = "First"
        if not NAME_REGEX.match(postData['first']):
            errors["First name contains invalid characters or spaces."] = "First"
        if not NAME_REGEX.match(postData['last']):
            errors["Last name contains invalid characters or spaces."] = "Last"
        if len(postData['last']) < 2:
            errors["Last name cannot be blank!"] = "Last"
        if len(postData['email']) < 2:
            errors["Email cannot be blank!"] = "Email"
        if (User.objects.filter(email=postData["email"])):
            errors["Email already in use"] = "Email"
        if not EMAIL_REGEX.match(postData['email']):
            errors["Invalid Email Address!"] = "Email"
        elif User.objects.filter(email = postData["email"]).count() > 0:
            errors["Email address already exists in database!"] = "Email"
        if len(postData['password']) < 8:
            errors["Password much be at least 8 characters long"] = "PasswordEmail"
        if (postData['password']) != (postData['confirm']):
            errors["Passwords must match."] = "Password"
        return errors

    def loginvalidate(self, postData): #declare a controller to check for errors in your login process
        errors = {}
        if User.objects.filter(email=postData["email"]): #if the email the user enters matches 
            currentUser = User.objects.get(email=postData["email"]) #creates a variable called current user and sets the object equal to it
            tempPW = currentUser.password #sets the temporary PW to be the CurrentUser's pw
            if not bcrypt.checkpw(postData["password"].encode(), tempPW.encode()): #encrypts the password 
                errors["Invalid password"] = "password."
        else: 
            errors["Email address does not exist in database."] = "Email"
        return errors



class User(models.Model):
    first = models.CharField(max_length=30)
    last = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    objects = UserManager()

apps/loginReg/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect

from django.contrib import messages #imports messages for errors

from .models import * #imports everything from models

def index(request):
    if "userid" in request.session:  # if a session id is present
        print "userid in session" #print in the terminal to tell me
        return render(request,'success.html')
    else:                           #if there is no user in session
        print "no user in session"  #print it in the terminal
        return render (request, 'index.html') #and take the person back to the homepage

def register(request): #never renders a page, it only processes the registration 
    errors = User.objects.validate(request.POST) #creates a variable and assigns the validate object to it, which contains everything in request.post
    if len(errors) > 0: #if there are any errors (which is determined in models)
        for error in errors: #for each error in the list of errors
            messages.error(request,error) #print messages of the error
        return redirect ('/')
    pwhash= bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt()) #hashing password and setting a variable for it
    newUser = User.objects.create(first=request.POST['first'], last=request.POST['last'], email= request.POST['email'], password = pwhash) #create a user out of the information passed in the registration form and set it to a variable of newUser
    request.session["userid"] = newUser.id  #set session id to newuser id
    request.session["first"] = newUser.first #set the first name attached to the session to the newUser's first name
    return redirect('/success')

def login(request): #never renders a page, it only processes the login 
    errors = User.objects.loginvalidate(request.POST) #setting a variable of errors equal to all of the errors gathered from the models page
    if len(errors) > 0: #if there are any errors present
        for error in errors:
            messages.error(request,error) #tell us with the messages function
        return redirect ('/')
    else:
        print "got here"
        user = User.objects.filter(email=request.POST['email'])[0]  #run query to filter for email equal to one in the databast. A list is returned. [0] calls that place in the list. Then you need to use key/value for dictionary
        request.session["userid"] = user.id #set session id to be the userid
        request.session["first"] = user.first 
        return redirect("/success")
    

def logout(request, methods='POST'):
    request.session.clear() #clears session
    return redirect('/')

def success(request):
    user = request.session["userid"] #gets the user from the database
    return render(request,'success.html')

apps/loginReg/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Login and Registration Form</title>
</head>

<body>

    <div id="wrapper">
        <h1>Registration</h1>
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
        <div id="form">
            <form action='/register' method='POST'>
                {% csrf_token %}
                First Name<input type='text' name='first'> 
                Last Name<input type='text' name='last'> 
                Email:<input type="email" name="email">
                Password:<input type="password" name="password">
                <input type="hidden" name="action" value="register"> 
                Confirm Password:<input type="password" name="confirm">
                <input type="submit" value="Submit">
            </form>
        </div>
        <h1>Login</h1>

        {% if form.errors %}
        <p>username or password not correct</p>
        {% endif %}
    

        <form action='/login' method='POST'>
            {% csrf_token %}
            Email:<input type="email" name="email">
            Password:<input type="password" name="password">
            <input type="submit" value="Submit">
        </form>
    </div>
</body>

</html>

apps/loginReg/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Success! Welcome, {{request.session.first}}!</h1>
    <p>Successfully registered (or logged in)!</p>

    <button> <a href="/logout">Logout</a></button>
    <a href="{%url 'examThree:index' %}">YOU'RE GOING TO PASS THIS TIME/LETS PLAN A TRIP! </a>
</body>
</html>